export * from './user/userRoute.js'
export * from './properties/propertyRoute.js'
export * from './auth/authRoute.js'
export * from './message/messageRoute.js'
export * from './employee/employeeRoute.js'
export * from './room/roomRoute.js'